apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-deployment
  namespace: asemmohamed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab
  template:
    metadata:
      labels:
        app: lab
    spec:
      containers:
      - name: lab
        image: asemmohamed321/newlab:4
        ports:
        - containerPort: 5000
