apiVersion: v1
kind: Service
metadata:
  name: jenkins-lab-service
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30055
